# Generated by Django 4.2.6 on 2023-10-18 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='material_info',
            field=models.TextField(default='There is no info on the materials'),
        ),
        migrations.AddField(
            model_name='product',
            name='model_info',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
