# Generated by Django 4.2.6 on 2023-10-21 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_product_model_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_details',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='media/product_images/'),
        ),
    ]
